name: Build and Release Module

on:
  workflow_dispatch: # Trigger manually from GitHub Actions UI

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the latest tag, or set to v1.0.0 if no tags exist
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "v1.0.0")
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Extract version and version code
        id: extract_version
        run: |
          latest_tag=${{ env.latest_tag }}
          
          # Check if this is the first release (v1.0.0)
          if [ "$latest_tag" == "v1.0.0" ]; then
            new_version="v1.0.0"
            new_version_code="1000"
          else
            # Increment version
            IFS='.' read -r major minor patch <<< "${latest_tag//v/}"
            patch=$((patch + 1))
            new_version="v$major.$minor.$patch"
            new_version_code=$((patch + 1000))
          fi

          echo "New version: $new_version"
          echo "New version code: $new_version_code"
          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "new_version_code=$new_version_code" >> $GITHUB_ENV

      - name: Update module.prop and update.json (only if version changes)
        run: |
          version_changed=false
          # Update version and versionCode in module.prop
          if grep -q "version=${{ env.latest_tag }}" module.prop; then
            sed -i "s/version=${{ env.latest_tag }}/version=${{ env.new_version }}/g" module.prop
            version_changed=true
          fi
          if grep -q "versionCode=[0-9]*" module.prop; then
            sed -i "s/versionCode=[0-9]*/versionCode=${{ env.new_version_code }}/g" module.prop
            version_changed=true
          fi

          # Update version and versionCode in update.json
          if grep -q "version\": \"${{ env.latest_tag }}\"" update.json; then
            sed -i "s/version\": \"${{ env.latest_tag }}\"/version\": \"${{ env.new_version }}\"/g" update.json
            version_changed=true
          fi
          if grep -q "versionCode\": [0-9]*" update.json; then
            sed -i "s/versionCode\": [0-9]*/versionCode\": ${new_version_code}/g" update.json
            version_changed=true
          fi

          # Update zipUrl in update.json
          if grep -q "zipUrl\": \"https://github.com/TheBizarreAbhishek/F23_Feature_Enhancer/releases/download/${{ env.latest_tag }}" update.json; then
            sed -i "s|\"zipUrl\": \".*\"|\"zipUrl\": \"https://github.com/TheBizarreAbhishek/F23_Feature_Enhancer/releases/download/${{ env.new_version }}/F23_Feature_Enhancer-${{ env.new_version }}.zip\"|g" update.json
            version_changed=true
          fi

          # If version changed, commit changes
          if [ "$version_changed" == "true" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add module.prop update.json
            git commit -m "Update version to ${{ env.new_version }} and version code to ${{ env.new_version_code }}"
            git push
          else
            echo "No changes in version or version code, skipping commit."
          fi

      - name: Create new tag for the release
        run: |
          git tag ${{ env.new_version }}
          git push origin ${{ env.new_version }}

      - name: Build zip file for the release
        run: |
          # Replace this with your actual zip build command
          mkdir -p release
          zip -r release/F23_Feature_Enhancer-${{ env.new_version }}.zip * # Adjust path if necessary

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.new_version }}
          name: "F23_Feature_Enhancer-${{ env.new_version }}"
          body: "Release notes for version ${{ env.new_version }}"
          files: release/F23_Feature_Enhancer-${{ env.new_version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
