name: Package, Update Version, and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Only trigger for semantic version tags

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Tag Info and Version Code
        id: tag_info
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          VERSION_CODE=$((1000 + $(echo $TAG_NAME | sed 's/v//; s/\.//g')))
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV
          echo "version_code=$VERSION_CODE" >> $GITHUB_ENV

      - name: Update module.prop
        run: |
          sed -i "s/^version=.*/version=${{ env.tag_name }}/" module.prop
          sed -i "s/^versionCode=.*/versionCode=${{ env.version_code }}/" module.prop

      - name: Update update.json
        run: |
          jq ".version = \"${{ env.tag_name }}\" |
              .versionCode = ${{ env.version_code }} |
              .zipUrl = \"https://github.com/TheBizarreAbhishek/F23_Feature_Enhancer/releases/download/${{ env.tag_name }}/F23_Feature_Enhancer-${{ env.tag_name }}.zip\"" \
            update.json > tmp.json && mv tmp.json update.json

      - name: Set up Zip Archive
        run: |
          mkdir package
          cp -r ./* package/
          cd package
          zip -r ../F23_Feature_Enhancer-${{ env.tag_name }}.zip .
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          title: "F23 Feature Enhancer ${{ env.tag_name }}"
          files: F23_Feature_Enhancer-${{ env.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
