name: Create and Publish Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Get current version tag
      id: get_version
      run: |
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "latest_tag=$latest_tag" >> $GITHUB_ENV
        IFS='.' read -r -a version_parts <<< "${latest_tag#v}"
        version_parts[2]=$((version_parts[2] + 1))
        new_version="v${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
        echo "new_version=$new_version" >> $GITHUB_ENV
        echo "New version: $new_version"

    - name: Create ZIP of module
      run: |
        zip_name="F23_Feature_Enhancer-${{ env.new_version }}.zip"
        zip -r "$zip_name" . -x ".git*" ".github*" "$zip_name"
        echo "zip_name=$zip_name" >> $GITHUB_ENV
        echo "Created $zip_name"

    - name: Create Git tag
      run: |
        git tag ${{ env.new_version }}
        git push origin ${{ env.new_version }}

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.new_version }}
        files: ${{ env.zip_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
